# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Nicholas Malizia"
description:        ""

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://nmalizia.github.io/blog"
author:             "Nicholas Malizia"
twitter:
  username:         "nrmalizia"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "https://nmalizia.github.io/blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/blog/about"
  - name:           "CV"
    href:           "/resume"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag